#!/bin/bash
#=================================================
# File name: init-settings.sh
# Description: This script will be executed during the first boot
# Author: SuLingGG
# Blog: https://mlapp.cn
#=================================================

# Set default theme to luci-theme-argon
uci set luci.main.mediaurlbase='/luci-static/argon'

# 设置DHCP服务器
uci set dhcp.@dnsmasq[0].local='/ycslan/'
uci set dhcp.@dnsmasq[0].domain='ycslan'

# 其他自定义设置
# DHCP设置（用以配置DHCP服务，变量值根据网络拓扑结构填写）
# 启用DHCP
uci set dhcp.lan.ignore='0'
# 网络地址起始分配基址
uci set dhcp.lan.start='1'
# 客户端数量（注意：使用MACVLAN的容器会占用局域网IP，注意避开）
uci set dhcp.lan.limit='226'
# 租约时间（整数+时间单位。最短不能小于2m）
uci set dhcp.lan.leasetime='5m'
# 强制使用此服务器分配IP
uci set dhcp.lan.force='1'
# 子网掩码、网关和DNS
uci add_list dhcp.lan.dhcp_option='1,255.255.255.0'
uci add_list dhcp.lan.dhcp_option='3,200.56.72.248'
uci add_list dhcp.lan.dhcp_option='6,200.56.72.251'

exit 0
