#!/bin/bash
#=================================================
# File name: init-settings.sh
# Description: This script will be executed during the first boot
# Author: SuLingGG
# Blog: https://mlapp.cn
#=================================================

# Set default theme to luci-theme-argon
uci set luci.main.mediaurlbase='/luci-static/argon'

# 设置DHCP服务器
uci set dhcp.@dnsmasq[0].local='/ycslan/'
uci set dhcp.@dnsmasq[0].domain='ycslan'

# 其他自定义设置
# DHCP设置（用以配置DHCP服务，变量值根据网络拓扑结构填写）

# 启用DHCP
uci set dhcp.lan.ignore='0'
# 网络地址起始分配基址
uci set dhcp.lan.start='1'
# 客户端数量（注意：使用MACVLAN的容器会占用局域网IP，注意避开）
uci set dhcp.lan.limit='226'
# 租约时间（整数+时间单位。最短不能小于2m）
uci set dhcp.lan.leasetime='5m'
# 强制使用此服务器分配IP
uci set dhcp.lan.force='1'
# 子网掩码、网关和DNS
uci add_list dhcp.lan.dhcp_option='1,255.255.255.0'
uci add_list dhcp.lan.dhcp_option='3,200.56.72.248'
uci add_list dhcp.lan.dhcp_option='6,200.56.72.251'
# 禁用DHCP_IPv6服务
uci set dhcp.lan.dhcpv6='disabled'
uci set dhcp.lan.ra='disabled'
uci set dhcp.lan.ndp='disabled'

uci add dhcp host
uci set dhcp.@host[-1].name='GL-AP'   # 主机名，可自定义
uci add_list dhcp.@host[-1].mac=='94:83:C4:4C:5C:38 '   # 设备的 MAC 地址。建议设备使用自身MAC
uci set dhcp.@host[-1].ip='200.56.72.240'   # 想要绑定的静态IP。IP必须在子网范围内！
uci set dhcp.@host[-1].leasetime='7d'   # 租约时间不得低于2m
