#!/bin/bash
#=================================================
# File name: init-settings.sh
# Description: This script will be executed during the first boot
# Author: SuLingGG
# Blog: https://mlapp.cn
#=================================================

# Set default theme to luci-theme-argon
uci set luci.main.mediaurlbase='/luci-static/argon'

# 设置DHCP服务器
uci set dhcp.@dnsmasq[0].local='/ycslan/'
uci set dhcp.@dnsmasq[0].domain='ycslan'

# 其他自定义设置


exit 0
